#ifndef PROMPTACHCOMMANDLINEPARSER_GLOBAL_H
#define PROMPTACHCOMMANDLINEPARSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROMPTACHCOMMANDLINEPARSER_LIBRARY)
#define PROMPTACHCOMMANDLINEPARSER_EXPORT Q_DECL_EXPORT
#else
#define PROMPTACHCOMMANDLINEPARSER_EXPORT Q_DECL_IMPORT
#endif

#endif // PROMPTACHCOMMANDLINEPARSER_GLOBAL_H
