#ifndef PROMPTACHSETTINGSBACKEND_GLOBAL_H
#define PROMPTACHSETTINGSBACKEND_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROMPTACHSETTINGSBACKEND_LIBRARY)
#define PROMPTACHSETTINGSBACKEND_EXPORT Q_DECL_EXPORT
#else
#define PROMPTACHSETTINGSBACKEND_EXPORT Q_DECL_IMPORT
#endif

#endif // PROMPTACHSETTINGSBACKEND_GLOBAL_H
